from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import IncidentViewSet

# Initialize the DefaultRouter and register the IncidentViewSet with it
# This setup automatically creates routes for standard viewset actions.
router = DefaultRouter()
router.register(r'monitoring', IncidentViewSet, basename='')

# Define custom URL patterns for the dashboard feature
# This allows for retrieving incidents with specific date filters directly via URL.
dashboard_urls = [
    # Custom URL for the dashboard view, capturing day, month, and year as URL parameters
    path('dashboard/<int:day>/<int:month>/<int:year>/', IncidentViewSet.as_view({'get': 'dashboard'}), name='dashboard'),
]

urlpatterns = [
    # Include all the routes generated by the router
    # This includes routes for creating, listing, retrieving, updating, and deleting incidents.
    path('', include(router.urls)),
    
    # Include the custom dashboard route
    # This route is designed to fetch incident data for specific dates.
    path('', include(dashboard_urls)),
]
